# Use root/example as user/password credentials
#version: '3.1'

services:

  db:
    image: mysql
      # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
      # (this is just an example, not intended to be a production configuration)
    command: 
    - --default-authentication-plugin=mysql_native_password
    - --innodb_force_recovery=0 #para criar registro de horas
    - --default_time_zone=America/Sao_Paulo #esse é para fazer o registro da hora
    restart: always
    volumes:
      - ~/.volume-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: juanigor
      MYSQL_DATABASE: base_de_dados


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:3306








#version: "3"
#services:
 # mysql_cursos:
 # container_name: mysql_cursos
  #hostname: mysql_cursos
 # image: mysql
  #restart: always
  #command:
    #- --default-authentication-plugin=mysql_native_password
   # #- --character-set-server=utf8mb4
    #- --collation-server=utf8mb4_unicode_ci
  #volumes:
      #- ~/.volume-mysql:/var/lib/mysql
  #ports:
  #  - 8080:3306
  #environment:
   # MYSQL_ROOT_PASSWORD: senha
   # MYSQL_DATABASE: base_de_dados
   # MYSQL_USER: usuario
   # MYSQL_PASSWORD: senha